version: '3.8'
services:
  auth-service:
    container_name: auth-service
    image: auth-service
    build:
      context: ./
      target: debug
    ports:
      - 3000:3000
    env_file:
      - docker-compose.env
    volumes:
      - .:/auth-service
      - /auth-service/node_modules
    depends_on:
      - user-service
      - users-database
  user-service:
    container_name: user-service
    image: user-service
    volumes:
      - ../user-service:/user-service
      - /user-service/node_modules
    build:
      context: ../user-service
      target: debug
    environment:
      - USER_SERVICE_PORT=3005
      - AUTH_SERVICE_PORT=3000
      - DATABASE_HOST=users-database
    ports:
      - 3005:3005
    depends_on:
      - users-database

  users-database:
    image: mysql
    container_name: users-database
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
